version: "3.7"

services:
  app:
    image: gradle:8.1.0-jdk17
    working_dir: /app
    volumes:
      - .:/app
      - gradle-cache:/home/gradle/.gradle
    networks:
      - app_net
    env_file:
      - docker.env
    ports:
      - 8080:8080
      - 5005:5005
    command: gradle bootRun
    links:
      - db:database.com
    depends_on:
      - db

  test:
    image: gradle:8.1.0-jdk17
    working_dir: /app
    volumes:
      - .:/app
      - gradle-cache:/home/gradle/.gradle
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - app_net
    command: gradle clean check

  db:
    image: biarms/mysql:5.7
    restart: always
    command: --default-authentication-plugin=mysql_native_password --bind-address=0.0.0.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wefine_db
    ports:
      - "3306:3306"
    networks:
      - app_net
networks:
  app_net:

volumes:
  gradle-cache:
  db-cache:
